# Generated by Django 4.0.3 on 2022-03-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Board Comment', 'verbose_name_plural': 'Board Comment'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Board Comment',
        ),
    ]
