# Generated by Django 4.0.3 on 2022-03-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.IntegerField(default=0, verbose_name='답글위치'),
        ),
    ]
