# Generated by Django 4.0.3 on 2022-03-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posts',
        ),
    ]
