# Generated by Django 4.0.3 on 2022-03-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=17, unique=True, verbose_name='아이디')),
                ('profile_img', models.ImageField(null=True, upload_to='profile', verbose_name='프로필사진')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='모임명')),
                ('member', models.CharField(max_length=256, null=True, verbose_name='소속회원')),
                ('manager', models.CharField(max_length=8, null=True, verbose_name='총무')),
                ('account', models.CharField(max_length=256, null=True, verbose_name='계좌번호')),
                ('level', models.CharField(choices=[('2', 'Lv2_회원'), ('1', 'Lv1_관리자'), ('0', 'lv0_개발자')], default=2, max_length=18, verbose_name='등급')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
