# Generated by Django 4.0.3 on 2022-03-23 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    # 현재 모든 유저에 대해 Profile을 만들어주자.
    # settings.AUTH_USER_MODEL = 'auth.User'
    auth_user_model = settings.AUTH_USER_MODEL.split('.')
    # *는 언팩킹함
    # apps.get_model()로 모델을 가져올 때는 (앱, 모델 클래스)를 인자로 입력
    User = apps.get_model(*auth_user_model)
    Profile = apps.get_model('users', 'Profile')

    for user in User.objects.all():
        print('create profile for user#{}'.format(user.pk))
        Profile.objects.create(user=user)

def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=17, unique=True, verbose_name='아이디')),
                ('level', models.CharField(choices=[('2', 'Lv2_회원'), ('1', 'Lv1_관리자'), ('0', 'lv0_개발자')], default=2, max_length=18, verbose_name='등급')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='모임명')),
                ('member', models.CharField(blank=True, max_length=256, verbose_name='소속회원')),
                ('manager', models.CharField(blank=True, max_length=8, verbose_name='총무')),
                ('account', models.CharField(blank=True, max_length=20, verbose_name='계좌번호')),
                ('profile_img', models.ImageField(blank=True, default='default.jpg', upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
